import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'
import { CharacterProvider } from './state/CharacterProvider'
import { createDefaultCharacter } from './constants/defaults'
import { ACTIONS, HERITAGES, PLAYBOOK_LIST } from './constants/playbooks'
import { BACKUP_KEY, readStoredCharacter, STORAGE_KEY } from './lib/storage'
import { parseCharacterFile, serializeCharacter } from './lib/serialize'
import { characterReducer } from './state/characterReducer'
function renderApp() {
  return render(
    <CharacterProvider>
      <App />
    </CharacterProvider>,
  )
}
async function tab(user: ReturnType<typeof userEvent.setup>, name: string) {
  if (!screen.queryByRole('navigation', { name: 'シートのセクション' }))
    await user.click(within(screen.getByRole('group', { name: '表示モード' })).getByRole('button', { name: '編集' }))
  await user.click(within(screen.getByRole('navigation', { name: 'シートのセクション' })).getByRole('button', { name }))
}
async function chooseBook(user: ReturnType<typeof userEvent.setup>, book: string) {
  await tab(user, '初期設定')
  await user.selectOptions(screen.getByLabelText('プレイブック'), book)
}
beforeEach(() => {
  window.localStorage.clear()
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(createDefaultCharacter('cutter')))
  vi.spyOn(window, 'confirm').mockReturnValue(true)
  // jsdomにはdialogの開閉APIがないため、open属性と初期フォーカスを再現する。
  HTMLDialogElement.prototype.showModal = function () {
    this.open = true
    this.querySelector<HTMLButtonElement>('button[autofocus]')?.focus()
  }
  HTMLDialogElement.prototype.close = function () {
    this.open = false
  }
})
afterEach(() => {
  cleanup()
  vi.restoreAllMocks()
  Reflect.deleteProperty(HTMLDialogElement.prototype, 'showModal')
  Reflect.deleteProperty(HTMLDialogElement.prototype, 'close')
})
describe('基本7種の操作', () => {
  it('出自の選択肢と選択後に地域の特徴を示し、地域名と家族の詳細を保存する', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '初期設定')
    const select = screen.getByRole('combobox', { name: '出自' })
    expect(select.getAttribute('aria-describedby')).toBeNull()
    expect(screen.queryByRole('link', { name: /出自の地域設定/ })).toBeNull()
    select.focus()
    await user.tab()
    expect(document.activeElement).toBe(screen.getByRole('textbox', { name: '出自の詳細' }))
    await user.tab()
    expect(document.activeElement).toBe(screen.getByRole('combobox', { name: '経歴' }))
    await user.tab()
    expect(document.activeElement).toBe(screen.getByRole('textbox', { name: '経歴の詳細' }))
    for (const heritage of HERITAGES) {
      expect(within(select).getByRole('option', { name: `${heritage.name}：${heritage.summary}` })).toBeTruthy()
      await user.selectOptions(select, heritage.id)
      const description = screen.getByText(heritage.description)
      expect(select.getAttribute('aria-describedby')).toBe(description.id)
    }
    await user.selectOptions(select, '')
    expect(screen.queryByText(HERITAGES[5].description)).toBeNull()
    expect(select.getAttribute('aria-describedby')).toBeNull()
    await user.selectOptions(select, 'akoros')
    await user.type(screen.getByRole('textbox', { name: '出自の詳細' }), '港で荷運びをする一家')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByText('Akoros')).toBeTruthy()
    expect(screen.queryByText(/Akoros：/)).toBeNull()
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.identity.heritageId).toBe('akoros')
    expect(saved?.identity.heritageDetail).toBe('港で荷運びをする一家')
  })
  it('固定点を維持してアクション欄だけで初期配分を確定し、成長分を編集・保存できる', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '初期設定')
    expect(screen.getByRole('heading', { name: 'アクション' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'キャラクター作成を完了' })).toBeNull()
    expect(screen.queryByRole('button', { name: '初期アクションを再設定' })).toBeNull()
    expect(screen.queryByText(/作成済み|技能ポイントを4点|残り：\d+点|ポイントの割り振りについて|成長後は通常3/)).toBeNull()
    expect(screen.getAllByRole('img', { name: /プレイブック固定・変更不可/ })).toHaveLength(3)
    const fixed = screen.getByRole('img', { name: 'Command 1（プレイブック固定・変更不可）' })
    expect(screen.queryByRole('button', { name: 'Command 1' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'Skirmish 2' })).toBeNull()
    await user.click(fixed)
    expect(document.activeElement).not.toBe(fixed)
    expect(screen.getByRole('button', { name: 'Skirmish 3' }).hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Hunt 1' }))
    await user.click(screen.getByRole('button', { name: 'Hunt 1' }))
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByRole('img', { name: '指揮（Command）：1' })).toBeTruthy()
    expect(screen.getByRole('img', { name: '乱戦（Skirmish）：2' })).toBeTruthy()
    expect(screen.getByRole('img', { name: '狩り（Hunt）：0' })).toBeTruthy()

    await tab(user, '初期設定')
    const summary = screen.getByRole('complementary', { name: 'アクションの配分' })
    expect(within(summary).getByText('0/4点')).toBeTruthy()
    const confirm = screen.getByRole('button', { name: '初期配分を確定' })
    expect(confirm.hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Hunt 2' }))
    expect(within(summary).getByText('2/4点')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'Study 2' }))
    expect(within(summary).getByText('4/4点')).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Tinker 1' }).hasAttribute('disabled')).toBe(true)
    expect(confirm.hasAttribute('disabled')).toBe(false)
    await user.click(confirm)
    expect(screen.getByRole('button', { name: '初期配分を修正' })).toBeTruthy()
    expect(screen.getByRole('img', { name: 'Hunt 2（初期配分・修正で変更）' })).toBeTruthy()
    for (const action of ACTIONS) {
      const fourth = screen.getByRole('button', { name: `${action.name} 4` })
      expect(fourth.hasAttribute('disabled')).toBe(false)
      await user.click(fourth)
      expect(fourth.getAttribute('aria-pressed')).toBe('true')
    }
    await user.click(screen.getByRole('button', { name: 'シート' }))
    for (const action of ACTIONS) {
      expect(screen.getByRole('img', { name: `${action.ja}（${action.name}）：4` })).toBeTruthy()
    }
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.abilities).toHaveLength(0)
    for (const action of ACTIONS) expect(saved?.ratings[action.id]).toBe(4)
    expect(saved?.initialActionRatings?.hunt).toBe(2)
    expect(saved).not.toHaveProperty('creationComplete')
    const raw = window.localStorage.getItem(STORAGE_KEY)
    expect(raw).toBeTruthy()
    expect(JSON.parse(raw ?? '{}')).not.toHaveProperty('creationComplete')
  }, 15000)
  it('初期配分の訂正・キャンセルでは成長分を保持し、成長分を含む上限4を守る', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '初期設定')
    await user.click(screen.getByRole('button', { name: 'Hunt 2' }))
    await user.click(screen.getByRole('button', { name: 'Study 2' }))
    await user.click(screen.getByRole('button', { name: '初期配分を確定' }))
    await user.click(screen.getByRole('button', { name: 'Hunt 4' }))
    await user.click(screen.getByRole('button', { name: 'Tinker 4' }))
    const summary = screen.getByRole('complementary', { name: 'アクションの配分' })
    expect(within(summary).getByText('6点')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: '初期配分を修正' }))
    expect(screen.getByRole('button', { name: 'Tinker 1' }).hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Hunt 2' }))
    expect(within(summary).getByText('3/4点')).toBeTruthy()
    expect(screen.getByRole('button', { name: '初期配分を確定' }).hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('button', { name: '訂正をやめる' }))
    expect(within(summary).getByText('4/4点')).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Hunt 4' }).getAttribute('aria-pressed')).toBe('true')
    await user.click(screen.getByRole('button', { name: '初期配分を修正' }))
    await user.click(screen.getByRole('button', { name: 'Hunt 2' }))
    await user.click(screen.getByRole('button', { name: 'Survey 1' }))
    await user.click(screen.getByRole('button', { name: '初期配分を確定' }))
    expect(within(summary).getByText('6点')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByRole('img', { name: '狩り（Hunt）：3' })).toBeTruthy()
    expect(screen.getByRole('img', { name: '観察（Survey）：1' })).toBeTruthy()
    expect(screen.getByRole('img', { name: '工作（Tinker）：4' })).toBeTruthy()
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.initialActionRatings?.hunt).toBe(1)
    expect(saved?.ratings.hunt).toBe(3)
  }, 15000)
  it('専用タブを外し、クルー名と質問例を残して以前の詳細を保存する', async () => {
    const user = userEvent.setup()
    const character = createDefaultCharacter('cutter')
    character.crew.name = '旧クルー'
    character.crew.notes = '以前のクルーメモ'
    character.crew.roster = [{ id: 'member', name: '仲間', role: '協力者', note: '旧記録', player: true }]
    character.score.planId = 'stealth'
    character.score.detail = '以前の作戦メモ'
    character.gatherNotes = { 'cutter:0': '以前の情報収集メモ' }
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(character))
    renderApp()
    await tab(user, '初期設定')
    expect(screen.queryByRole('button', { name: '作戦メモ' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'クルー' })).toBeNull()
    const crewName = screen.getByRole('textbox', { name: '所属クルー名' })
    expect((crewName as HTMLInputElement).value).toBe('旧クルー')
    await user.clear(crewName)
    await user.type(crewName, '新クルー')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByText('新クルー')).toBeTruthy()
    const questions = screen.getByText('情報収集の質問例')
    await user.click(questions)
    for (const question of PLAYBOOK_LIST[0].gatherInfo) expect(screen.getByText(question)).toBeTruthy()
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.crew).toEqual({ ...character.crew, name: '新クルー' })
    expect(saved?.score).toEqual(character.score)
    expect(saved?.gatherNotes).toEqual(character.gatherNotes)
  })
  it('技能と分離した経験値欄で四つのXPを更新し、画面切り替え後も保持する', async () => {
    const user = userEvent.setup()
    renderApp()
    const skills = screen.getByRole('region', { name: '技能・抵抗' })
    const experience = screen.getByRole('region', { name: '経験値' })
    expect(within(skills).getAllByRole('img')).toHaveLength(12)
    expect(within(skills).queryByRole('button')).toBeNull()

    for (const name of ['PLAYBOOK', 'INSIGHT', 'PROWESS']) {
      await user.click(within(experience).getByRole('button', { name: `${name} 2` }))
    }
    const resolve = within(experience).getByRole('button', { name: 'RESOLVE 1' })
    resolve.focus()
    await user.keyboard(' ')
    expect(resolve.getAttribute('aria-pressed')).toBe('true')
    expect(within(skills).getByRole('img', { name: '乱戦（Skirmish）：2' })).toBeTruthy()

    await tab(user, '初期設定')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    const restored = within(screen.getByRole('region', { name: '経験値' }))
    expect(restored.getByRole('button', { name: 'RESOLVE 1' }).getAttribute('aria-pressed')).toBe('true')
    for (const name of ['PLAYBOOK', 'INSIGHT', 'PROWESS']) {
      expect(restored.getByRole('button', { name: `${name} 2` }).getAttribute('aria-pressed')).toBe('true')
    }
  })
  it(
    'シートのアクションは表示のみで、編集の変更とXP操作を反映する',
    async () => {
      const user = userEvent.setup()
      const character = createDefaultCharacter('cutter')
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(character))
      renderApp()

      const rating = screen.getByRole('img', { name: '狩り（Hunt）：0' })
      expect(screen.queryByRole('button', { name: /^Hunt / })).toBeNull()
      expect(screen.queryByRole('button', { name: /^Skirmish / })).toBeNull()
      await user.click(rating)
      await user.keyboard('{Enter} ')
      expect(screen.getByRole('img', { name: '狩り（Hunt）：0' })).toBeTruthy()

      await user.click(screen.getByRole('button', { name: 'INSIGHT 2' }))
      await tab(user, '初期設定')
      await user.click(screen.getByLabelText('Hunt 1'))
      await user.tab()
      expect(document.activeElement).toBe(screen.getByLabelText('Hunt 2'))
      await user.keyboard('{Enter}')
      await user.click(screen.getByRole('button', { name: 'シート' }))
      expect(screen.getByRole('img', { name: '狩り（Hunt）：2' })).toBeTruthy()
      expect(screen.getByRole('button', { name: 'INSIGHT 2' }).getAttribute('aria-pressed')).toBe('true')

      await tab(user, '初期設定')
      await user.click(screen.getByLabelText('Hunt 2'))
      await user.click(screen.getByRole('button', { name: 'シート' }))
      expect(screen.getByRole('img', { name: '狩り（Hunt）：1' })).toBeTruthy()
    },
    15000,
  )
  it.each(PLAYBOOK_LIST)('$titleを選んで固有能力を取得しシートに表示する', async (book) => {
    const user = userEvent.setup()
    renderApp()
    await chooseBook(user, book.id)
    for (const action of ACTIONS) {
      const initial = book.initialRatings[action.id] ?? 0
      for (let index = 1; index <= 4; index++) {
        if (index <= initial) {
          expect(screen.getByRole('img', { name: `${action.name} ${index}（プレイブック固定・変更不可）` })).toBeTruthy()
          expect(screen.queryByRole('button', { name: `${action.name} ${index}` })).toBeNull()
          continue
        }
        const dot = screen.getByRole('button', { name: `${action.name} ${index}` })
        expect(dot.getAttribute('aria-pressed')).toBe(String(index <= initial))
        expect(dot.hasAttribute('disabled')).toBe(index > 2)
      }
    }
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: `取得：${book.abilities[0].name}` }))
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByRole('heading', { name: book.title })).toBeTruthy()
    expect(screen.getByText(book.abilities[0].name)).toBeTruthy()
    expect(screen.getByText(book.xpTrigger)).toBeTruthy()
    expect(screen.getByRole('button', { name: book.items[0].ja })).toBeTruthy()
  }, 15000)
  it('プレイブック変更は確認なしで確定しアクションと特殊能力を初期化する', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '初期設定')
    await user.type(screen.getByLabelText('名前'), '人物')
    await user.click(screen.getByLabelText('Hunt 1'))
    expect(screen.getByLabelText('Hunt 1').getAttribute('aria-pressed')).toBe('true')
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: `取得：${PLAYBOOK_LIST[0].abilities[0].name}` }))
    expect(screen.queryByText('未取得（編集の特殊能力から取得できます）')).toBeNull()
    await tab(user, '初期設定')
    await user.selectOptions(screen.getByLabelText('プレイブック'), 'hound')
    expect((screen.getByLabelText('プレイブック') as HTMLSelectElement).value).toBe('hound')
    expect((screen.getByLabelText('名前') as HTMLInputElement).value).toBe('人物')
    expect(screen.queryByRole('region', { name: 'プレイブック変更の確認' })).toBeNull()
    expect(screen.getByRole('img', { name: 'Hunt 2（プレイブック固定・変更不可）' })).toBeTruthy()
    expect(screen.getByLabelText('Skirmish 1').getAttribute('aria-pressed')).toBe('false')
    await user.click(screen.getByLabelText('Hunt 4'))
    expect(screen.getByLabelText('Hunt 4').hasAttribute('disabled')).toBe(true)
    expect(within(screen.getByRole('complementary', { name: 'アクションの配分' })).getByText('0/4点')).toBeTruthy()
    await tab(user, '特殊能力')
    expect(screen.getByText('未取得（編集の特殊能力から取得できます）')).toBeTruthy()
  })
  it('知人との関係は編集で設定し、シートでは表示だけにする', async () => {
    const user = userEvent.setup()
    renderApp()
    const [first, second] = PLAYBOOK_LIST[0].friends
    expect(screen.getByRole('img', { name: `${first.name}：未選択` })).toBeTruthy()
    await tab(user, '初期設定')
    for (const relation of screen.getAllByRole('combobox', { name: /との関係$/ })) {
      expect(within(relation).getAllByRole('option').map((option) => option.textContent)).toEqual([
        '未選択', '親しい人物', 'ライバル',
      ])
      expect((relation as HTMLSelectElement).value).toBe('neutral')
    }
    await user.selectOptions(screen.getByLabelText(`${first.name}との関係`), 'friend')
    await user.selectOptions(screen.getByLabelText(`${second.name}との関係`), 'friend')
    expect((screen.getByLabelText(`${first.name}との関係`) as HTMLSelectElement).value).toBe(
      'neutral',
    )
    await user.selectOptions(screen.getByLabelText(`${first.name}との関係`), 'rival')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    const firstRival = screen.getByRole('img', { name: `${first.name}：ライバル` })
    expect(firstRival.textContent).toBe('△▼')
    expect(screen.getByRole('img', { name: `${second.name}：親しい人物` }).textContent).toBe('▲▽')
    expect(screen.queryByRole('button', { name: /：親しい人物|：ライバル/ })).toBeNull()
    expect(screen.queryByRole('combobox', { name: /との関係/ })).toBeNull()
    await user.click(firstRival)
    expect(document.activeElement).not.toBe(firstRival)
    await user.keyboard('{Enter} ')
    await tab(user, '初期設定')
    expect((screen.getByLabelText(`${first.name}との関係`) as HTMLSelectElement).value).toBe(
      'rival',
    )
    expect((screen.getByLabelText(`${second.name}との関係`) as HTMLSelectElement).value).toBe(
      'friend',
    )
    await user.selectOptions(screen.getByLabelText(`${first.name}との関係`), 'neutral')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByRole('img', { name: `${first.name}：未選択` }).textContent).toBe('△▽')
  })
  it('複数能力・Veteran・上限補正を表示する', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: '取得：Mule' }))
    await user.selectOptions(screen.getByLabelText('能力の取得元'), 'hound')
    await user.click(screen.getByRole('button', { name: '取得：Survivor' }))
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByText('Mule')).toBeTruthy()
    expect(screen.getByText('Survivor')).toBeTruthy()
    expect(screen.getByText('Veteran')).toBeTruthy()
    expect(screen.getByRole('button', { name: 'ストレス 10' })).toBeTruthy()
    expect(screen.getByRole('option', { name: '重 8' })).toBeTruthy()
  })
  it('能力の取り消しをキャンセルでき、取り消し後は再取得・保存できる', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: '取得：Mule' }))
    await user.type(screen.getByLabelText('Mule：メモ'), '訂正前のメモ')
    expect(screen.getByRole('button', { name: '取得済み：Mule' }).hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('button', { name: 'Mule 1の取得を取り消す' }))
    const dialog = screen.getByRole('dialog', { name: 'Muleの取得を取り消す' })
    expect(dialog.textContent).toContain('Load上限（軽／中／重）：5／7／8 → 3／5／6')
    await user.click(within(dialog).getByRole('button', { name: 'キャンセル' }))
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(document.activeElement).toBe(screen.getByRole('button', { name: 'Mule 1の取得を取り消す' }))
    expect((screen.getByLabelText('Mule：メモ') as HTMLTextAreaElement).value).toBe('訂正前のメモ')
    await user.click(screen.getByRole('button', { name: 'Mule 1の取得を取り消す' }))
    act(() => screen.getByRole('dialog').dispatchEvent(new Event('cancel', { cancelable: true })))
    expect(screen.queryByRole('dialog')).toBeNull()
    expect(screen.getByRole('region', { name: 'Mule 1' })).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'Mule 1の取得を取り消す' }))
    await user.click(screen.getByRole('button', { name: '取り消しを確定' }))
    expect(screen.queryByRole('region', { name: 'Mule 1' })).toBeNull()
    expect(screen.getByRole('button', { name: '取得：Mule' }).hasAttribute('disabled')).toBe(false)
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.queryByText('Mule')).toBeNull()
    expect(screen.getByRole('option', { name: '重 6' })).toBeTruthy()
    act(() => window.dispatchEvent(new Event('pagehide')))
    expect(readStoredCharacter().character?.abilities).toEqual([])
    cleanup()
    renderApp()
    await tab(user, '特殊能力')
    expect(screen.queryByRole('region', { name: 'Mule 1' })).toBeNull()
    await user.click(screen.getByRole('button', { name: '取得：Mule' }))
    expect((screen.getByLabelText('Mule：メモ') as HTMLTextAreaElement).value).toBe('')
    act(() => window.dispatchEvent(new Event('pagehide')))
    expect(readStoredCharacter().character?.abilities).toHaveLength(1)
  })
  it('Veteranの取り消しでストレスを補正し、他の能力とXPを保持する', async () => {
    const user = userEvent.setup()
    let character = characterReducer(createDefaultCharacter('cutter'), { type: 'ability.add', definitionId: 'cutter:mule' })
    character = characterReducer(character, { type: 'ability.add', definitionId: 'hound:survivor' })
    character = characterReducer(character, { type: 'resource', resource: 'stress', value: 10 })
    character = characterReducer(character, { type: 'resource', resource: 'playbook', value: 4 })
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(character))
    renderApp()
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: 'Survivor 2の取得を取り消す' }))
    expect(screen.getByRole('dialog', { name: 'Survivorの取得を取り消す' }).textContent).toContain('現在のストレス：10 → 9')
    await user.click(screen.getByRole('button', { name: '取り消しを確定' }))
    expect(screen.getByRole('region', { name: 'Mule 1' })).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.queryByText('Survivor')).toBeNull()
    expect(screen.queryByRole('button', { name: /取得を取り消す/ })).toBeNull()
    expect(screen.getByRole('button', { name: 'ストレス 9' }).getAttribute('aria-pressed')).toBe('true')
    expect(screen.queryByRole('button', { name: 'ストレス 10' })).toBeNull()
    act(() => window.dispatchEvent(new Event('pagehide')))
    expect(readStoredCharacter().character?.xp.playbook).toBe(4)
  })
  it('追加取得した能力を個別に取り消し、自由記入能力も取り消せる', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '特殊能力')
    await user.selectOptions(screen.getByLabelText('能力の取得元'), 'hound')
    await user.click(screen.getByRole('button', { name: '取得：Ghost Hunter' }))
    await user.click(screen.getByRole('button', { name: '追加取得：Ghost Hunter' }))
    const first = screen.getByRole('region', { name: 'Ghost Hunter 1' })
    const second = screen.getByRole('region', { name: 'Ghost Hunter 2' })
    await user.selectOptions(within(first).getByLabelText('Ghost Hunter の選択内容'), 'ghost-form')
    await user.selectOptions(within(second).getByLabelText('Ghost Hunter の選択内容'), 'mind-link')
    await user.type(within(second).getByLabelText('Ghost Hunter：狩猟動物の名前・特徴'), '残す動物')
    await user.click(within(first).getByRole('button', { name: 'Ghost Hunter 1の取得を取り消す' }))
    await user.click(screen.getByRole('button', { name: '取り消しを確定' }))
    expect(screen.getAllByRole('region', { name: /Ghost Hunter/ })).toHaveLength(1)
    expect((screen.getByLabelText('Ghost Hunter の選択内容') as HTMLSelectElement).value).toBe('mind-link')
    expect((screen.getByLabelText('Ghost Hunter：狩猟動物の名前・特徴') as HTMLTextAreaElement).value).toBe('残す動物')
    await user.click(screen.getByRole('button', { name: '自由記入の能力を追加' }))
    await user.type(screen.getByLabelText('能力名'), '仮の能力')
    await user.type(screen.getByLabelText('能力の効果'), '仮の効果')
    await user.click(screen.getByRole('button', { name: '仮の能力 2の取得を取り消す' }))
    await user.click(screen.getByRole('button', { name: '取り消しを確定' }))
    expect(screen.queryByRole('textbox', { name: '能力名' })).toBeNull()
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.abilities).toHaveLength(1)
    expect(saved?.abilities[0].choice).toBe('mind-link')
    expect(saved?.abilities[0].notes).toBe('残す動物')
  })
  it('Leechの薬品枠とLoad超過を扱う', async () => {
    const user = userEvent.setup()
    renderApp()
    await chooseBook(user, 'leech')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    await user.click(screen.getByRole('button', { name: '弾帯1' }))
    await user.selectOptions(screen.getByLabelText('弾帯1 使用枠 3'), 'Grenade')
    expect((screen.getByLabelText('弾帯1 使用枠 1') as HTMLSelectElement).value).toBe('')
    expect((screen.getByLabelText('弾帯1 使用枠 3') as HTMLSelectElement).value).toBe('Grenade')
    await user.selectOptions(screen.getByLabelText('仕事のLoad'), 'light')
    await user.click(screen.getByRole('button', { name: '良質な破壊道具' }))
    await user.click(screen.getByRole('button', { name: '仕掛け道具 2' }))
    expect(screen.getByText(/使用Load 5 \/ 3/)).toBeTruthy()
    expect(screen.getByText('選択した上限を超えています。卓の裁定を確認してください。')).toBeTruthy()
    await tab(user, '装備')
    expect(screen.getByText(/使用Load 5 \/ 3/)).toBeTruthy()
    expect(screen.getByText('選択した上限を超えています。卓の裁定を確認してください。')).toBeTruthy()
    await user.selectOptions(screen.getByLabelText('仕事のLoad'), 'normal')
    expect(screen.getByText(/使用Load 5 \/ 5/)).toBeTruthy()
    expect(screen.queryByText('選択した上限を超えています。卓の裁定を確認してください。')).toBeNull()
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByText(/使用Load 5 \/ 5/)).toBeTruthy()
    expect(screen.getByRole('button', { name: '良質な破壊道具' }).getAttribute('aria-pressed')).toBe('true')
  })
  it('個別の傷を確定ボタンなしで保持し、治療・XP・資産の上限を表示する', async () => {
    const user = userEvent.setup()
    renderApp()
    expect(
      within(screen.getByRole('group', { name: 'PLAYBOOK' })).getAllByRole('button'),
    ).toHaveLength(8)
    expect(
      within(screen.getByRole('group', { name: 'INSIGHT' })).getAllByRole('button'),
    ).toHaveLength(6)
    expect(screen.queryByRole('button', { name: 'COIN 5' })).toBeNull()
    expect(screen.getByRole('button', { name: 'STASH 40' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: '治療クロック 5' })).toBeNull()
    expect(screen.queryByRole('button', { name: /傷.*を記録/ })).toBeNull()
    await user.type(screen.getByLabelText('レベル1の傷 1（効果低下）'), '打撲')
    await user.type(screen.getByLabelText('レベル1の傷 2（効果低下）'), '疲労')
    await tab(user, '状態')
    expect((screen.getByLabelText('レベル1の傷 1（効果低下）') as HTMLInputElement).value).toBe('打撲')
    expect((screen.getByLabelText('レベル1の傷 2（効果低下）') as HTMLInputElement).value).toBe('疲労')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect((screen.getByLabelText('レベル1の傷 1（効果低下）') as HTMLInputElement).value).toBe(
      '打撲',
    )
    expect((screen.getByLabelText('レベル1の傷 2（効果低下）') as HTMLTextAreaElement).value).toBe('疲労')
  })
  it('傷の追記・訂正・削除を画面切り替えと再読み込み後も保持する', async () => {
    const user = userEvent.setup()
    const view = renderApp()
    const first = screen.getByRole('textbox', { name: 'レベル1の傷 1（効果低下）' })
    await user.type(first, '打撲')
    expect(document.activeElement).toBe(first)
    expect(screen.getByRole('textbox', { name: 'レベル1の傷 1（効果低下）' })).toBe(first)
    await user.type(screen.getByRole('textbox', { name: 'レベル1の傷 2（効果低下）' }), '疲労')
    await tab(user, '状態')
    const second = screen.getByRole('textbox', { name: 'レベル1の傷 2（効果低下）' })
    expect((second as HTMLInputElement).value).toBe('疲労')
    await user.clear(second)
    const edited = screen.getByRole('textbox', { name: 'レベル1の傷 1（効果低下）' })
    await user.clear(edited)
    await user.type(edited, '左腕の打撲')
    await user.type(screen.getByRole('textbox', { name: 'レベル3の傷（手助け・自分を追い込む）' }), '骨折')
    await user.type(screen.getByRole('textbox', { name: '致命的な傷・結果' }), '重篤')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    act(() => window.dispatchEvent(new Event('pagehide')))
    expect(readStoredCharacter().character?.harm).toMatchObject({
      level1: ['左腕の打撲', ''], level3: '骨折', fatal: '重篤',
    })
    view.unmount()
    renderApp()
    expect((screen.getByRole('textbox', { name: 'レベル1の傷 1（効果低下）' }) as HTMLTextAreaElement).value).toBe('左腕の打撲')
    expect((screen.getByRole('textbox', { name: 'レベル1の傷 2（効果低下）' }) as HTMLTextAreaElement).value).toBe('')
    expect((screen.getByRole('textbox', { name: 'レベル3の傷（手助け・自分を追い込む）' }) as HTMLTextAreaElement).value).toBe('骨折')
    expect((screen.getByRole('textbox', { name: '致命的な傷・結果' }) as HTMLTextAreaElement).value).toBe('重篤')
  })
  it('各数値を直接増減・入力でき、上下限とシートへの反映・保存を保つ', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '状態')
    expect(screen.queryByRole('button', { name: '履歴' })).toBeNull()
    expect(screen.queryByLabelText('理由')).toBeNull()
    expect(screen.queryByRole('combobox', { name: '変更する対象' })).toBeNull()
    expect(screen.queryByRole('button', { name: '増減を適用' })).toBeNull()
    for (const [label, max] of [
      ['ストレス', 9], ['コイン', 4], ['貯蓄', 40], ['プレイブックXP', 8],
      ['Insight XP', 6], ['Prowess XP', 6], ['Resolve XP', 6],
    ] as const) {
      const input = screen.getByRole('spinbutton', { name: label })
      const decrease = screen.getByRole('button', { name: `${label}を1減らす` })
      const increase = screen.getByRole('button', { name: `${label}を1増やす` })
      expect(decrease.hasAttribute('disabled')).toBe(true)
      increase.focus()
      await user.keyboard('{Enter}')
      expect((input as HTMLInputElement).value).toBe('1')
      await user.clear(input)
      await user.type(input, String(max + 1))
      expect((input as HTMLInputElement).value).toBe(String(max))
      expect(increase.hasAttribute('disabled')).toBe(true)
      await user.click(decrease)
      expect((input as HTMLInputElement).value).toBe(String(max - 1))
    }
    const stress = screen.getByRole('spinbutton', { name: 'ストレス' })
    await user.clear(stress)
    await user.type(stress, '2')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect(screen.getByRole('button', { name: 'ストレス 2' }).getAttribute('aria-pressed')).toBe('true')
    expect(screen.getByRole('button', { name: 'ストレス 3' }).getAttribute('aria-pressed')).toBe('false')
    expect(screen.getByRole('button', { name: 'COIN 3' }).getAttribute('aria-pressed')).toBe('true')
    expect(screen.getByRole('button', { name: 'PLAYBOOK 7' }).getAttribute('aria-pressed')).toBe('true')
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved).toMatchObject({ stress: 2, coin: 3, stash: 39,
      xp: { playbook: 7, insight: 5, prowess: 5, resolve: 5 } })
    await tab(user, 'データ')
    expect(screen.queryByText('記録件数')).toBeNull()
  })
  it('傷の表・トラウマ・治療・鎧を編集し、能力補正と以前のクロックを保持する', async () => {
    const user = userEvent.setup()
    let character = createDefaultCharacter('cutter')
    for (const definitionId of ['cutter:vigorous', 'hound:survivor', 'cutter:battleborn']) {
      character = characterReducer(character, { type: 'ability.add', definitionId })
    }
    character.clocks = [{ id: 'old-clock', name: '以前の計画', total: 6, filled: 3 }]
    character.equipment.armor = 1
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(character))
    const view = renderApp()
    await tab(user, '状態')
    const harm = screen.getByRole('table', { name: '傷の記録' })
    expect(within(harm).getAllByRole('textbox')).toHaveLength(5)
    expect(within(harm).getAllByRole('rowheader').map((cell) => cell.textContent)).toEqual(['3', '2', '1'])
    expect(screen.queryByRole('heading', { name: '長期プロジェクト・クロック' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'クロックを追加' })).toBeNull()
    expect(screen.getByText('自由記入のトラウマ', { selector: 'summary' }).closest('details')?.open).toBe(false)
    for (const name of ['冷酷', '過去の恐怖', '執着', '猜疑']) {
      await user.click(screen.getByRole('checkbox', { name }))
    }
    expect(screen.getByRole('checkbox', { name: '無謀' }).hasAttribute('disabled')).toBe(true)
    await user.click(screen.getByRole('checkbox', { name: '猜疑' }))
    await user.click(screen.getByText('自由記入のトラウマ', { selector: 'summary' }))
    await user.type(screen.getByRole('textbox', { name: '自由記入のトラウマ' }), '孤立')
    await user.click(screen.getByRole('button', { name: 'トラウマを追加' }))
    const healing = screen.getByRole('spinbutton', { name: '治療' })
    expect((healing as HTMLInputElement).value).toBe('1')
    expect(screen.getByRole('button', { name: '治療を1減らす' }).hasAttribute('disabled')).toBe(true)
    await user.clear(healing)
    await user.type(healing, '9')
    expect((healing as HTMLInputElement).value).toBe('4')
    expect(screen.getByRole('spinbutton', { name: 'ストレス' }).getAttribute('max')).toBe('10')
    await user.click(screen.getByRole('checkbox', { name: '通常鎧' }))
    await user.click(screen.getByRole('checkbox', { name: '特殊鎧' }))
    await user.click(screen.getByRole('button', { name: '特殊鎧の使用をリセット' }))
    expect((screen.getByRole('checkbox', { name: '通常鎧' }) as HTMLInputElement).checked).toBe(true)
    expect((screen.getByRole('checkbox', { name: '特殊鎧' }) as HTMLInputElement).checked).toBe(false)
    act(() => window.dispatchEvent(new Event('pagehide')))
    const saved = readStoredCharacter().character
    expect(saved?.clocks).toEqual(character.clocks)
    expect(saved?.traumas).toEqual(['cold', 'haunted', 'obsessed', '孤立'])
    const roundTrip = parseCharacterFile(serializeCharacter(saved ?? character))
    expect(roundTrip.ok && roundTrip.character.clocks).toEqual(character.clocks)
    view.unmount()
    renderApp()
    expect(screen.getByRole('button', { name: '治療クロック 4' }).getAttribute('aria-pressed')).toBe('true')
    expect((screen.getByRole('checkbox', { name: '孤立（取り込み・自由記入）' }) as HTMLInputElement).checked).toBe(true)
  })
  it('LurkのExpertiseの対象とWhisperの儀式メモを入力する', async () => {
    const user = userEvent.setup()
    renderApp()
    await chooseBook(user, 'lurk')
    await tab(user, '特殊能力')
    await user.click(screen.getByRole('button', { name: '取得：Expertise' }))
    await user.selectOptions(screen.getByLabelText('Expertise の選択内容'), 'prowl')
    await user.selectOptions(screen.getByLabelText('能力の取得元'), 'whisper')
    await user.click(screen.getByRole('button', { name: '取得：Ritual' }))
    await user.type(screen.getByLabelText('Ritual：習得した儀式・手順・代償'), '霊を呼ぶ儀式')
    await user.click(screen.getByRole('button', { name: 'シート' }))
    expect((screen.getByLabelText('Expertise の選択内容') as HTMLSelectElement).value).toBe('prowl')
    expect(
      (screen.getByLabelText('Ritual：習得した儀式・手順・代償') as HTMLTextAreaElement).value,
    ).toBe('霊を呼ぶ儀式')
  })
  it('保存人物をシート内に表示し、上部は表示切り替えだけにする', async () => {
    const user = userEvent.setup()
    const character = createDefaultCharacter('spider')
    character.identity.name = '保存人物'
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(character))
    renderApp()
    expect(screen.getByRole('heading', { name: 'SPIDER' })).toBeTruthy()
    expect(screen.getByText('保存人物')).toBeTruthy()
    expect(screen.getByRole('banner').textContent).toBe('シート編集')
    expect(within(screen.getByRole('banner')).getAllByRole('button')).toHaveLength(2)
    expect(screen.queryByText('エッジ')).toBeNull()
    expect(screen.queryByRole('button', { name: 'エッジ 2' })).toBeNull()
    await user.click(screen.getByRole('button', { name: '編集' }))
    expect((screen.getByLabelText('名前') as HTMLInputElement).value).toBe('保存人物')
    expect(screen.getByRole('banner').textContent).toBe('シート編集')
    expect(screen.getByRole('button', { name: '編集' }).getAttribute('aria-pressed')).toBe('true')
  })
  it('壊れたJSONの取り込みで現在のキャラクターを維持する', async () => {
    const user = userEvent.setup()
    renderApp()
    await tab(user, '初期設定')
    await user.type(screen.getByLabelText('名前'), '維持する人物')
    await tab(user, 'データ')
    const file = new File(['{broken'], 'broken.json', { type: 'application/json' })
    Object.defineProperty(file, 'text', { value: async () => '{broken' })
    await user.upload(screen.getByLabelText('キャラクターJSONファイル'), file)
    expect(await screen.findByText(/JSONを読み込めません/)).toBeTruthy()
    expect(window.confirm).not.toHaveBeenCalled()
    await tab(user, '初期設定')
    expect((screen.getByLabelText('名前') as HTMLInputElement).value).toBe('維持する人物')
  })
  it('バックアップがあっても復元ボタンを表示せず、JSONの取り込みと元データの保管を行う', async () => {
    const user = userEvent.setup()
    const previousBackup = createDefaultCharacter('whisper')
    window.localStorage.setItem(BACKUP_KEY, serializeCharacter(previousBackup))
    renderApp()
    await tab(user, '初期設定')
    await user.type(screen.getByLabelText('名前'), '取り込み前の人物')
    await tab(user, 'データ')
    expect(screen.queryByRole('button', { name: '取り込み前のシートに戻す' })).toBeNull()
    const imported = createDefaultCharacter('hound')
    imported.identity.name = '取り込んだ人物'
    const json = serializeCharacter(imported)
    const file = new File([json], 'hound.json', { type: 'application/json' })
    Object.defineProperty(file, 'text', { value: async () => json })
    await user.upload(screen.getByLabelText('キャラクターJSONファイル'), file)
    expect(screen.getByRole('status').textContent).toContain('JSONを読み込みました。')
    expect(screen.queryByRole('button', { name: '取り込み前のシートに戻す' })).toBeNull()
    expect(parseCharacterFile(window.localStorage.getItem(BACKUP_KEY) ?? '')).toMatchObject({
      ok: true, character: { playbookId: 'cutter', identity: { name: '取り込み前の人物' } },
    })
    await tab(user, '初期設定')
    expect((screen.getByLabelText('名前') as HTMLInputElement).value).toBe('取り込んだ人物')
    expect((screen.getByLabelText('プレイブック') as HTMLSelectElement).value).toBe('hound')
  })
})
